# Generated by Django 5.0.7 on 2024-08-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crmsystem", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
