# Generated by Django 5.0.7 on 2024-08-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmsystem", "0004_lead_ad_alter_product_cost_contract_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="customers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ad",
            name="leads_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ad",
            name="profit",
            field=models.IntegerField(default=0),
        ),
    ]
