# Generated by Django 5.0.7 on 2024-08-04 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmsystem', '0004_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.contract')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crmsystem.lead')),
            ],
        ),
    ]
