# Generated by Django 5.0.7 on 2024-08-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crmsystem", "0005_ad_customers_count_ad_leads_count_ad_profit"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
    ]
