# Generated by Django 5.0.7 on 2024-08-09 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.contract",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        limit_choices_to={"is_customer": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leads.lead",
                    ),
                ),
            ],
        ),
    ]
