# Generated by Django 5.0.7 on 2024-08-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advertisement",
            options={"permissions": (("view_statistics", "Can view ads statistics"),)},
        ),
    ]
